apiVersion: v1
kind: Service              # 1
metadata:
  name: my-driver-service
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 9999         # 5
  selector:                # 6
    app:  my-driver-service       # 7