apiVersion: v1
kind: Service             
metadata:
  name: my-driver-service
spec:
  type: LoadBalancer      
  ports:
  - port: 6666             
    protocol: TCP         
    targetPort: 6666
    name: server    
  - port: 6667           
    protocol: TCP         
    targetPort: 6667      
    name: hadoop
  - port: 6668             
    protocol: TCP          
    targetPort: 6668        
    name: spark
  - port: 6669            
    protocol: TCP         
    targetPort: 6669      
    name: jupyter
  - port: 6070          
    protocol: TCP          
    targetPort: 6070         
    name: sonarqube
  selector:                
    app:  my-driver-deployment      