apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-driver-deployment
  labels:
    app: my-driver-deployment
spec:
  selector:
     matchLabels:
       app: my-driver-deployment
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-driver-deployment
    spec:
      containers:
        - image: hobo965859229/driver:v2.0
          imagePullPolicy: Always
          name: my-driver-deployment
          env:
            - name: JUPYTER_NOTEBOOK
              value: "http://my-jupyter"
            - name: SPARK
              value: "http://my-spark"
            - name: SONARQUBE
              value: "http://my-sonarqube"
            - name: HADOOP
              value: "http://hadoop-hdfs-master"
          ports:
            - containerPort: 6666
            - containerPort: 6667
            - containerPort: 6668
            - containerPort: 6669
            - containerPort: 6070