apiVersion: v1
kind: Service             
metadata:
  name: section-driver-service
spec:
  type: LoadBalancer      
  ports:
  - port: 6666             
    protocol: TCP         
    targetPort: 6666
    name: server    
  - port: 6070          
    protocol: TCP         
    targetPort: 6070    
    name: hadoop
  - port: 6766             
    protocol: TCP          
    targetPort: 6766        
    name: spark
  - port: 6866           
    protocol: TCP         
    targetPort: 6866      
    name: jupyter
  - port: 6966       
    protocol: TCP          
    targetPort: 6966        
    name: sonarqube
  selector:                
    app:  section-driver-deployment      