apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-driver-deployment
  labels:
    app: section-driver-deployment
spec:
  selector:
     matchLabels:
       app: section-driver-deployment
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: section-driver-deployment
    spec:
      containers:
        - image: hobo965859229/driver:v3.0
          imagePullPolicy: Always
          name: section-driver-deployment
          env:
            - name: JUPYTER_NOTEBOOK
              value: "http://section-jupyter"
            - name: SPARK
              value: "http://section-spark"
            - name: SONARQUBE
              value: "http://section-sonarqube"
            - name: HADOOP
              value: "http://hadoop-hdfs-master"
          ports:
            - containerPort: 6666
            - containerPort: 6766
            - containerPort: 6866
            - containerPort: 6966
            - containerPort: 6070