apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jupyter-notebook
  labels:
    app: my-jupyter-notebook
spec:
  selector:
     matchLabels:
       app: my-jupyter-notebook
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-jupyter-notebook
    spec:
      containers:
        - image: hobo965859229/my-juypter-notebook:v1.0
          imagePullPolicy: Always
          name: my-jupyter-notebook
          ports:
            - containerPort: 8888