apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jupyter
  labels:
    app: my-jupyter
spec:
  selector:
     matchLabels:
       app: my-jupyter
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-jupyter
    spec:
      containers:
        - image: hobo965859229/jupyter-notebook:v1.0
          imagePullPolicy: Always
          name: my-jupyter
          ports:
            - containerPort: 8888