apiVersion: v1
kind: Service
metadata:
  name: section-jupyter
spec:
  type: LoadBalancer      
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: section-jupyter