apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sonarqube
  labels:
    app: my-sonarqube
spec:
  selector:
     matchLabels:
       app: my-sonarqube
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-sonarqube
    spec:
      containers:
        - image: hobo965859229/sonarqube:v1.0
          imagePullPolicy: Always
          name: my-sonarqube
          ports:
            - containerPort: 9000