apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-spark
  labels:
    app: section-spark
spec:
  selector:
     matchLabels:
       app: section-spark
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: section-spark
    spec:
      containers:
        - image: hobo965859229/spark:v1.0
          imagePullPolicy: Always
          name: section-spark
          ports:
            - containerPort: 8080